@startuml

title __TILED's Class Diagram__\n

  package  {
    package Tiled {
      class Tile {
          - location : Point2D
          - image : BufferedImage
          - flags : int
          - collision : boolean
          - destination : boolean
          - y : int
          - x : int
          - distance : int
          + Tile()
          + Tile()
          + Tile()
          + draw()
          + isCollision()
          + isDestination()
          + getDistance()
          + getY()
          + getX()
          + getNearTiles()
          + equals()
          + hashCode()
          + toString()
          + getLocation()
      }
    }
  }
  

  package  {
    package Tiled {
      class TiledLayer {
          - ID : int
          - name : String
          - data : ArrayList<Integer>
          - width : int
          - height : int
          + TiledLayer()
          + getWidth()
          + setWidth()
          + getHeight()
          + setHeight()
          + getID()
          + getName()
          + getData()
      }
    }
  }
  

  package  {
    package Tiled {
      class TiledMap {
          {static} - FLIP_H_FLAG : int
          {static} - FLIP_V_FLAG : int
          {static} - FLIP_D_FLAG : int
          ~ tilesImages : ArrayList<BufferedImage>
          - cacheImage : BufferedImage
          - collision : boolean[][]
          - layers : ArrayList<TiledLayer>
          - tilesets : ArrayList<TiledTileSet>
          - tilesByLayer : ArrayList<ArrayList<Tile>>
          + TiledMap()
          + getTilesByLayer()
          + redrawCache()
          + draw()
          + drawCache()
          + getCollision()
      }
    }
  }
  

  package  {
    package Tiled {
      class TiledTile {
          - tileHeight : int
          - tileWidth : int
          - ID : int
          + TiledTile()
          + getTileHeight()
          + getTileWidth()
          + getID()
          + setID()
      }
    }
  }
  

  package  {
    package Tiled {
      class TiledTileMap {
          - width : int
          - height : int
          + TiledTileMap()
          + getWidth()
          + getHeight()
      }
    }
  }
  

  package  {
    package Tiled {
      class TiledTileSet {
          - name : String
          - image : BufferedImage
          - firstgid : int
          - tileCount : int
          - columns : int
          + TiledTileSet()
          + getFirstgid()
          + getTileCount()
          + getColumns()
          + getImage()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
